name: Generate content & deploy to pages

run-name: Generating a new version of the website and CV!

on: [push]

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
      - run: pip install -r requirements.txt
      - run: python website_generator.py
      - uses: TiesdeKok/html2pdf@master #markwilson/html2pdf@v1.0
        with:
          htmlPath: 'public/resume.html'
          pdfName: 'public/Vitae.pdf'
      - uses: stefanzweifel/git-auto-commit-action@v4
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      - name: copy resume PDF to remote host
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CV_LOC_HOST }}
          username: ${{ secrets.CV_LOC_USERNAME }}
          password: ${{ secrets.CV_LOC_PW }}
          port: ${{ secrets.CV_LOC_PORT }}
          source: "public/Vitae.pdf"
          target: ${{ secrets.CV_LOC_FOLDER }}
          tar_tmp_path : ${{ secrets.CV_LOC_FOLDER }}